language: python
dist: trusty
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
    packages:
      - llvm-4.0
      - llvm-4.0-dev
      - clang-4.0
      - libidn2-0-dev
      - libssh2-1-dev
      - pkg-config
env:
  global:
    - CC=clang-4.0 CXX=clang++-4.0 RANLIB=llvm-ranlib-4.0 AR=llvm-ar-4.0 NM=llvm-nm-4.0 LD=ld.gold
    - CFLAGS=" -flto -B/usr/bin/ld.gold "
    - LDFLAGS=" -flto -B/usr/bin/ld.gold -fuse-ld=/usr/bin/ld.gold -Wl,-plugin-opt=save-temps "
before_install:
  - sudo ln -sf /usr/bin/ld.gold /usr/bin/ld
install:
  - curl https://curl.haxx.se/download/curl-7.54.0.tar.gz | tar xz
  - pushd curl-7.54.0
  - ./configure && make
  - file src/.libs/*
  - popd
  - curl https://curl.haxx.se/download/curl-7.53.0.tar.gz | tar xz
  - pushd curl-7.53.0
  - ./configure && make
  - file src/.libs/*
  - popd
  - CC=gcc CXX= RANLIB= AR= NM= LD= CFLAGS= LDFLAGS= pip install llvmlite pygraphviz networkx
script: python callflowdiff.py
