language: generic
env: 
install:
  - curl -sSL "http://apt.llvm.org/llvm-snapshot.gpg.key" | sudo -E apt-key add -
  - echo "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main" | sudo tee -a /etc/apt/sources.list > /dev/null
  - sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
  - sudo apt-get update
  - sudo apt-get install -y llvm-4.0 llvm-4.0-dev clang-4.0
  - CC=clang-4.0 CXX=clang++-4.0 RANLIB=llvm-ranlib-4.0 CFLAGS=" -flto -std=gnu99 " LDFLAGS=" -flto -fuse-ld=gold "
  - wget https://curl.haxx.se/download/curl-7.54.0.tar.gz
  - tar xf curl-7.54.0.tar.gz
  - pushd curl-7.54.0
  - ./configure
  - sed -i 's/-flto -fuse-ld=gold/ -flto -fuse-ld=gold -Wl,-plugin-opt=emit-llvm /g' Makefile src/Makefile
  - make V=1
  - file src/.libs/curl
  - ls -lah
  - ls -lah src/.libs
