language: generic
env: 
install:
  - curl -sSL "http://apt.llvm.org/llvm-snapshot.gpg.key" | sudo -E apt-key add -
  - echo "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main" | sudo tee -a /etc/apt/sources.list > /dev/null
  - sudo apt-get update
  - sudo apt-get install llvm-4.0 clang-4.0
  - CC=clang CXX=clang++ RANLIB=llvm-ranlib CFLAGS=" -flto -std=gnu99 " LDFLAGS=" -flto -fuse-ld=gold "
  - wget https://curl.haxx.se/download/curl-7.54.0.tar.gz
  - tar xf curl-7.54.0.tar.gz
  - pushd curl-7.54.0
  - ./configure
  - make
